server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
    loadbalancer:
      instances:
        STUDENT-SERVICE:
          - uri: http://localhost:8081
          - uri: http://localhost:8082
